### ISSUE TITLE
filtering bad words

### ISSUE THREAD

**Issue by codeing123** [d1loop/app#2]
add a feature to the app that filters bad words and links in the database

**Comment by itsrn** [comment]
Great idea! Gonna add that to the roadmap of the repository and give you credit.

**Comment by itsrn** [comment]
Added this feature to the app. Thanks a lot, @codeing123!
Hopefully, you'll bring more great ideas to the app!

**Comment by itsrn** [comment]
This feature is currently not available in v1. It will return in v1.5
